services:

  gateway:
    image: caddy:latest
    container_name: gateway
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
      - ./gateway/.well-known:/srv/.well-known
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - auth
    networks:
      - gateway
      - tphome-network
    restart: unless-stopped

  auth:
    build: ./auth
    container_name: tpcloud-auth
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - gateway
    restart: unless-stopped

  login:
    build: ./login
    container_name: tpcloud-login
    depends_on:
      - auth
    networks:
      - gateway
    restart: unless-stopped

  cloud:
    build: ./cloud
    container_name: tpcloud-frontend
    depends_on:
      - auth
    networks:
      - gateway
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - gateway
    restart: unless-stopped

networks:
  gateway:
    driver: bridge
  tphome-network:
    external: true
    name: tphome_tphome-network

volumes:
  caddy_data:
  caddy_config:
