services:
  auth:
    build: ./auth
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - gateway

  login:
    build: ./login
    depends_on:
      - auth
    networks:
      - gateway

  cloud:
    build: ./cloud
    depends_on:
      - auth
    networks:
      - gateway

  tphome:
    build: ./tphome
    env_file: .env
    depends_on:
      - auth
    networks:
      - gateway
      - tphome-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
  tphome-network:
    external: true
    name: tphome_tphome-network
