server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /auth/callback {
        try_files /auth/callback.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
